version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5

    working_directory: ~/vwc-site

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Installing Packages
          command: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: ./node_modules

      - run:
          name: Running Tests
          command: yarn test

      - deploy:
          name: Deploy to DigitalOcean
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST
              cd $PROJECT_NAME
              git pull -r origin master
              yarn
              yarn restart
            else
              echo "Not master branch, so not deploying"
            fi
