version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5

    working_directory: ~/vwc-site

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Installing packages
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: ./node_modules

      - run:
          name: Running tests
          command: yarn test

      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - store_test_results:
          path: test-results.xml

      - deploy:
          name: Deploy to DigitalOcean
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh $DEPLOY_USER@$DEPLOY_HOST
              yes
              cd $PROJECT_NAME
              git pull -r origin master
              yarn
              yarn restart
            else
              echo "Not master branch so not deploying"
            fi
