import Head from "next/head";
import { getProducts } from "../../utils/shopify";
import ProductCard from "../../components/product-card/ProductCard";
import styles from "./home.module.css";

export default function Home({ data }) {
  const products = data.products.edges;

  return (
    <>
      <Head>
        <title>Nextjs Shopify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.products}>
          {products.length ? (
            products.map((product) => (
              <ProductCard key={product.node.id} product={product} />
            ))
          ) : (
            <p>No products available at the moment.</p>
          )}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  try {
    const data = await getProducts();

    if (!data || !data.products || !data.products.edges) {
      throw new Error("Invalid data from Shopify API");
    }

    return {
      props: { data },
    };
  } catch (error) {
    console.error("Error fetching products:", error);
    return {
      props: { data: { products: { edges: [] } } },
    };
  }
};
