# This workflow will do a clean up modules that potentially got checked in that were not supposed to be.

name: cleanup

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Clean Up Action
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn disable:blog

    - uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        commit_user_name: GitHub Actions Bot
        commit_user_email: my-github-actions-bot@example.org
        commit_message: "GitHub Actions Bot Cleaning up dependencies"

        branch: ${{ github.head_ref }}

      env:
        CI: true