# This workflow will send messages

name: 'Welcome New Contributors'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hey @contributor_name, thanks for opening your first issue. We welcome you to the community and appreciate your dedication to enhance our application!'
          pr-message: 'Hey @contributor_name, thanks for opening your first Pull Request. This is an exciting time to contriubte to our open source appliucation. Keep up the great work! Someone will review it soon.'
